// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtKM4mh9rZhpFml1U_qDLOzpQZHwLqTiU',
    appId: '1:696960893106:web:5e1cecd39b66e4e7af49ab',
    messagingSenderId: '696960893106',
    projectId: 'sams-7a359',
    authDomain: 'sams-7a359.firebaseapp.com',
    storageBucket: 'sams-7a359.firebasestorage.app',
    measurementId: 'G-QSDMXVQ5PS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNRaEm5JkpDMy0c789Ga5H6ulcv55t-fI',
    appId: '1:696960893106:android:720aaff5a2010995af49ab',
    messagingSenderId: '696960893106',
    projectId: 'sams-7a359',
    storageBucket: 'sams-7a359.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC144d4vxEehPDSxDukeSSlk8wBwaVxoPs',
    appId: '1:696960893106:ios:3913259961537c4caf49ab',
    messagingSenderId: '696960893106',
    projectId: 'sams-7a359',
    storageBucket: 'sams-7a359.firebasestorage.app',
    iosBundleId: 'com.example.sams',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC144d4vxEehPDSxDukeSSlk8wBwaVxoPs',
    appId: '1:696960893106:ios:6a75a1d7f08edf74af49ab',
    messagingSenderId: '696960893106',
    projectId: 'sams-7a359',
    storageBucket: 'sams-7a359.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtKM4mh9rZhpFml1U_qDLOzpQZHwLqTiU',
    appId: '1:696960893106:web:52858e6222b3e0fbaf49ab',
    messagingSenderId: '696960893106',
    projectId: 'sams-7a359',
    authDomain: 'sams-7a359.firebaseapp.com',
    storageBucket: 'sams-7a359.firebasestorage.app',
    measurementId: 'G-VXP37ZQBZN',
  );
}
